site: David Klein
url:
title: David Klein
description: Description
twitter:
  username: diklein
  card: summary
  creator: diklein
author:
  twitter: diklein
  name: David Klein
  avatar:
  email: me@diklein.com
  url: diklein.com
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:year/:month/:day/:slug/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
